name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_ubuntu_test:
    name: asdf plugin test ubuntu
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: install dependencies
        run: sudo apt-get install libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev libsqlite3-dev
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: hl --version
  plugin_macos_test:
    name: asdf plugin test macos
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: install dependencies
        run: brew bundle
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: hl --version
